assigness: []
harvest_options:
  goldcopy: false
  path: s3://ooi-data
  refresh: true
  test: false
instrument: RS03AXPS-SF03A-4F-PCO2WA301
stream:
  method: streamed
  name: pco2w_a_battery_voltage
workflow_config:
  schedule: 0 0 * * *
